### ISSUE TITLE
Use environment variables

### ISSUE THREAD

**Issue by qjoly** [jseguillon/graftool#9]
To comply with rule 3 on 12 cloud factors, store parameters (e.g. Prometheus URL) in environment variables.

NB: Can be linked with #7 

[12facot](https://12factor.net/fr/config)

**Comment by jseguillon** [comment]
now fixed on main : https://github.com/jseguillon/graftool/commit/1df0177cf49c9de688e27ccfec60c35f105d0aa2

need doc so keeping open till README is published

**Comment by qjoly** [comment]
> now fixed on main : https://github.com/jseguillon/graftool/commit/1df0177cf49c9de688e27ccfec60c35f105d0aa2
> 
> need doc so keeping open till README is published

> By convention, but not rule, environment variable names are always capitalized.

[Source](https://www.cherryservers.com/blog/how-to-set-list-and-manage-linux-environment-variables)

**Comment by qjoly** [comment]
Fixed on [9c8c433](https://github.com/jseguillon/graftool/commit/9c8c433c33a4c5069687eb7caf5ca1ed4b6e619f)
